### ISSUE TITLE
Error while trying to run the bots on mainnet

### ISSUE THREAD

**Issue by FidelVe** [iconation/Daedric#3]
Both mainnet and testnet scores SCORES were created successfully:

* mainnet: cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f
* testnet: cxaaf89443375899cfc0c0cf746b6dc9eb295f286f

after creating the scores I am able to run the bots without any problems on the testnet, for example when executing `./scripts/bots/binance/icxusd/post.sh -n yeouido -s <password>` I get this result.

```shell
> Result:
 `-> Getting result for TxHash: 0x173a63b2f8bea2c0cd73560d5274725fb3abe0e5a1b4d6
0a4c7982f818c71344 ...
 `-> Transaction result: {
    "jsonrpc": "2.0",
    "result": {
        "txHash": "0x173a63b2f8bea2c0cd73560d5274725fb3abe0e5a1b4d60a4c7982f818c
71344",
        "blockHeight": "0xacbf10",
        "blockHash": "0x9fde16893cb029048c0196dfb8b1533ed4eba10f3dd673fa4053ca3c
0e9fa9d7",
        "txIndex": "0x1",
        "to": "cxaaf89443375899cfc0c0cf746b6dc9eb295f286f",
        "stepUsed": "0x21a48",
        "stepPrice": "0x2540be400",
        "cumulativeStepUsed": "0x21a48",
        "eventLogs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1"
    },
    "id": 1
}
```

On the other hand when I try to run the bots on the mainnet by executing this command `./scripts/bots/binance/icxusd/post.sh -n mainnet -s <password>` I get this result:

```shell
> Command:
$ tbears sendtx <(python ./scripts/score/dynamic_call/post.py mainnet 5390835579514824704) -c ./config/mainnet/tbears_cli_config.json -p f.6m9d9uPTPWPyn8k
> Result:
 `-> Got an error response
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "JSON schema validation error: 'to' has an invalid value"
    },
    "id": 1
} 
```

**Comment by Spl3en** [comment]
You should have a file called `./config/mainnet/score_address.txt`, could you make sure this file contains the address of your SCORE ? As you experienced an error when deploying your SCORE, this file may contain a wrong address.
Thanks!

**Comment by FidelVe** [comment]
Yes, the files has the correct SCORE address

```shell
$ cat config/mainnet/score_address.txt 
cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f
```

**Comment by Spl3en** [comment]
May you confirm there is no carriage return character at the end of the `./config/mainnet/score_address.txt` please ? (make sure your text editor doesn't add one when exiting the file)

 > 'to' has an invalid value

It seems to indicate that the score address is wrong

**Comment by FidelVe** [comment]
correct, there are no carriage return, there is only one line that ends at the last character of the address, I'm using vim.

>It seems to indicate that the score address is wrong

yes but as you can see when I run `cat` this is the result 
```
$ cat config/mainnet/score_address.txt 
cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f
```

here is the contract in the tracker
https://tracker.icon.foundation/contract/cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f

and this is the wallet that I used to create the contract 
https://tracker.icon.foundation/address/hxaec7c08d315f0ee53fff276b8f756e6f5e40564b

One thing Im noticing is that the contract says that the balance is 0 ICX, but the wallet has 77 ICX.

Could it be because the contract has no balance?

**Comment by Spl3en** [comment]
> Could it be because the contract has no balance?

No, otherwise you would have a different error.
You got a "JSON schema validation error", so there's something in the syntax that is wrong somewhere.
Could you post the content of your `calls/post.json` file, and also maybe trying to add a `print("<%s>" % score_address_txt)` [before this line](https://github.com/iconation/Daedric/blob/5f0dfe44508fc845822492c87537506351d08298/scripts/score/dynamic_call/post.py#L10) and launch the command again in order to figure out what is the value being read from the file ? (call it directly, `python ./script/score/dynamic_call/post.py mainnet 1234` for instance)
Thanks!

**Comment by FidelVe** [comment]
`calls/post.json`
```shell
{
    "jsonrpc": "2.0",
    "method": "icx_sendTransaction",
    "params": {
        "nid": "0x1",
        "version": "0x3",
        "stepLimit": "0x1000000",
        "nonce": "0x0",
        "to": "xxx",
        "dataType": "call",
        "data": {
            "method": "post",
            "params": {
                "value": "xxx"
            }
        }
    },
    "id": 1
}
```
this is the result of calling `post.py` with the `print` statement

```shell
python ./scripts/score/dynamic_call/post.py mainnet 1234
<./config/mainnet/score_address.txt>
{
    "jsonrpc": "2.0", 
    "method": "icx_sendTransaction", 
    "params": {
        "nid": "0x1", 
        "version": "0x3", 
        "stepLimit": "0x1000000", 
        "nonce": "0x0", 
        "to": "cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f\n", 
        "dataType": "call", 
        "data": {
            "method": "post", 
            "params": {
                "value": "1234"
           }
        }
    }, 
    "id": 1
}
```

indeed there is a carriage return at the end of the contract, but the file doesn't have one

![20200318_142205](https://user-images.githubusercontent.com/43641727/76994306-8dfb0980-6924-11ea-9046-5382ca06a63c.jpg)

**Comment by Spl3en** [comment]
Don't trust what you see, there is a carriage return not displayed by vim.
Remove the last character manually : 

`truncate -s-1 ./config/mainnet/score_address.txt`

Then you can check with an hexadecimal display : 

`cat ./config/mainnet/score_address.txt | hexdump -C`

**Comment by FidelVe** [comment]
`sed` results

```
$sed '$ s/.$//' ./config/mainnet/score_address.txt 
cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5
```

`cat` results

```
$ cat ./config/mainnet/score_address.txt | hexdump -C
00000000  63 78 33 64 61 65 37 64  66 38 39 62 30 65 65 31  |cx3dae7df89b0ee1|
00000010  61 30 61 66 30 39 61 39  34 36 38 62 37 61 65 37  |a0af09a9468b7ae7|
00000020  63 61 35 30 32 32 31 61  35 66 0a                 |ca50221a5f.|
0000002b
```
now this is the result of running the bot

```
$ ./scripts/bots/binance/icxusd/post.sh -n mainnet -s 'f.6m9d9uPTPWPyn8k'
> Command:
$ tbears sendtx <(python ./scripts/score/dynamic_call/post.py mainnet 5672149744753260544) -c ./config/mainnet/tbears_cli_config.json -p f.6m9d9uPTPWPyn8k
> Result:
 `-> Exception: Expecting value: line 1 column 1 (char 0) 
```

**Comment by Spl3en** [comment]
> 00000020  63 61 35 30 32 32 31 61  35 66 0a                 |ca50221a5f.|

As you can see, there is a remaining '0a' byte, which is the carriage return character. 

> sed '$ s/.$//' ./config/mainnet/score_address.txt 

Please redirect the output to the file, or do directly : 

`echo -ne "cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5" > ./config/mainnet/score_address.txt`

You should have something like this : ![https://i.imgur.com/WJ2UUvE.png](https://i.imgur.com/WJ2UUvE.png)

> Exception: Expecting value: line 1 column 1 (char 0) 

Please remove any "print" you added in the `post.py` file, only keep the `print(json.dumps(call))` at the end of the script... then everything should be working fine :)

**Comment by FidelVe** [comment]
```
$ echo -ne "cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f" > ./config/mainnet/score_address.txt
```

```
$ cat ./config/mainnet/score_address.txt | hexdump -C
00000000  63 78 33 64 61 65 37 64  66 38 39 62 30 65 65 31  |cx3dae7df89b0ee1|
00000010  61 30 61 66 30 39 61 39  34 36 38 62 37 61 65 37  |a0af09a9468b7ae7|
00000020  63 61 35 30 32 32 31 61  35 66                    |ca50221a5f|
0000002a
```
```
$ ./scripts/bots/binance/icxusd/post.sh -n mainnet -s 'f.6m9d9uPTPWPyn8k'
> Command:
$ tbears sendtx <(python ./scripts/score/dynamic_call/post.py mainnet 5685048322910744576) -c ./config/mainnet/tbears_cli_config.json -p f.6m9d9uPTPWPyn8k
> Result:
 `-> Got an error response
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32005,
        "message": "cx3dae7df89b0ee1a0af09a9468b7ae7ca50221a5f is inactive SCORE"
    },
    "id": 1
} 
```

Perfect now only to wait for the SCORE contract to be activated!.

Thank you @Spl3en sorry for the trouble! :see_no_evil:

**Comment by Spl3en** [comment]
Great!
No, it's actually my fault, I should really try to fix that error when the mainnet SCORE is deployed. It's the root of many mistakes.
Cheers!
